/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppMemoryRouteImport } from './routes/app.memory'
import { Route as AppJournalRouteImport } from './routes/app.journal'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as ApiUsageSummaryRouteImport } from './routes/api/usage-summary'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiMemoryRouteImport } from './routes/api/memory'
import { Route as ApiInsightsRouteImport } from './routes/api/insights'
import { Route as ApiDataRouteImport } from './routes/api/data'
import { Route as ApiConversationsRouteImport } from './routes/api/conversations'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiVoiceSessionRouteImport } from './routes/api/voice.session'
import { Route as ApiVoiceDeepgramTokenRouteImport } from './routes/api/voice.deepgram-token'
import { Route as ApiSpotifyTokenRouteImport } from './routes/api/spotify.token'
import { Route as ApiSpotifyRefreshRouteImport } from './routes/api/spotify.refresh'
import { Route as ApiMemoryDigestRouteImport } from './routes/api/memory.digest'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiUsageSummaryRoute = ApiUsageSummaryRouteImport.update({
  id: '/api/usage-summary',
  path: '/api/usage-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRoute = ApiMemoryRouteImport.update({
  id: '/api/memory',
  path: '/api/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsRoute = ApiInsightsRouteImport.update({
  id: '/api/insights',
  path: '/api/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSessionRoute = ApiVoiceSessionRouteImport.update({
  id: '/api/voice/session',
  path: '/api/voice/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceDeepgramTokenRoute = ApiVoiceDeepgramTokenRouteImport.update({
  id: '/api/voice/deepgram-token',
  path: '/api/voice/deepgram-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyTokenRoute = ApiSpotifyTokenRouteImport.update({
  id: '/api/spotify/token',
  path: '/api/spotify/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyRefreshRoute = ApiSpotifyRefreshRouteImport.update({
  id: '/api/spotify/refresh',
  path: '/api/spotify/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryDigestRoute = ApiMemoryDigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => ApiMemoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRoute
  '/api/data': typeof ApiDataRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/memory': typeof ApiMemoryRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/usage-summary': typeof ApiUsageSummaryRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/health': typeof AppHealthRoute
  '/app/journal': typeof AppJournalRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/notes': typeof AppNotesRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/': typeof AppIndexRoute
  '/api/memory/digest': typeof ApiMemoryDigestRoute
  '/api/spotify/refresh': typeof ApiSpotifyRefreshRoute
  '/api/spotify/token': typeof ApiSpotifyTokenRoute
  '/api/voice/deepgram-token': typeof ApiVoiceDeepgramTokenRoute
  '/api/voice/session': typeof ApiVoiceSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRoute
  '/api/data': typeof ApiDataRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/memory': typeof ApiMemoryRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/usage-summary': typeof ApiUsageSummaryRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/health': typeof AppHealthRoute
  '/app/journal': typeof AppJournalRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/notes': typeof AppNotesRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app': typeof AppIndexRoute
  '/api/memory/digest': typeof ApiMemoryDigestRoute
  '/api/spotify/refresh': typeof ApiSpotifyRefreshRoute
  '/api/spotify/token': typeof ApiSpotifyTokenRoute
  '/api/voice/deepgram-token': typeof ApiVoiceDeepgramTokenRoute
  '/api/voice/session': typeof ApiVoiceSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRoute
  '/api/data': typeof ApiDataRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/memory': typeof ApiMemoryRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/usage-summary': typeof ApiUsageSummaryRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/health': typeof AppHealthRoute
  '/app/journal': typeof AppJournalRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/notes': typeof AppNotesRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/': typeof AppIndexRoute
  '/api/memory/digest': typeof ApiMemoryDigestRoute
  '/api/spotify/refresh': typeof ApiSpotifyRefreshRoute
  '/api/spotify/token': typeof ApiSpotifyTokenRoute
  '/api/voice/deepgram-token': typeof ApiVoiceDeepgramTokenRoute
  '/api/voice/session': typeof ApiVoiceSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/callback'
    | '/api/chat'
    | '/api/conversations'
    | '/api/data'
    | '/api/insights'
    | '/api/memory'
    | '/api/settings'
    | '/api/tts'
    | '/api/usage-summary'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/health'
    | '/app/journal'
    | '/app/memory'
    | '/app/notes'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/'
    | '/api/memory/digest'
    | '/api/spotify/refresh'
    | '/api/spotify/token'
    | '/api/voice/deepgram-token'
    | '/api/voice/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/api/chat'
    | '/api/conversations'
    | '/api/data'
    | '/api/insights'
    | '/api/memory'
    | '/api/settings'
    | '/api/tts'
    | '/api/usage-summary'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/health'
    | '/app/journal'
    | '/app/memory'
    | '/app/notes'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app'
    | '/api/memory/digest'
    | '/api/spotify/refresh'
    | '/api/spotify/token'
    | '/api/voice/deepgram-token'
    | '/api/voice/session'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/callback'
    | '/api/chat'
    | '/api/conversations'
    | '/api/data'
    | '/api/insights'
    | '/api/memory'
    | '/api/settings'
    | '/api/tts'
    | '/api/usage-summary'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/health'
    | '/app/journal'
    | '/app/memory'
    | '/app/notes'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/'
    | '/api/memory/digest'
    | '/api/spotify/refresh'
    | '/api/spotify/token'
    | '/api/voice/deepgram-token'
    | '/api/voice/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConversationsRoute: typeof ApiConversationsRoute
  ApiDataRoute: typeof ApiDataRoute
  ApiInsightsRoute: typeof ApiInsightsRoute
  ApiMemoryRoute: typeof ApiMemoryRouteWithChildren
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiUsageSummaryRoute: typeof ApiUsageSummaryRoute
  ApiSpotifyRefreshRoute: typeof ApiSpotifyRefreshRoute
  ApiSpotifyTokenRoute: typeof ApiSpotifyTokenRoute
  ApiVoiceDeepgramTokenRoute: typeof ApiVoiceDeepgramTokenRoute
  ApiVoiceSessionRoute: typeof ApiVoiceSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/memory': {
      id: '/app/memory'
      path: '/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journal': {
      id: '/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/usage-summary': {
      id: '/api/usage-summary'
      path: '/api/usage-summary'
      fullPath: '/api/usage-summary'
      preLoaderRoute: typeof ApiUsageSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory': {
      id: '/api/memory'
      path: '/api/memory'
      fullPath: '/api/memory'
      preLoaderRoute: typeof ApiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights': {
      id: '/api/insights'
      path: '/api/insights'
      fullPath: '/api/insights'
      preLoaderRoute: typeof ApiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/session': {
      id: '/api/voice/session'
      path: '/api/voice/session'
      fullPath: '/api/voice/session'
      preLoaderRoute: typeof ApiVoiceSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/deepgram-token': {
      id: '/api/voice/deepgram-token'
      path: '/api/voice/deepgram-token'
      fullPath: '/api/voice/deepgram-token'
      preLoaderRoute: typeof ApiVoiceDeepgramTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/token': {
      id: '/api/spotify/token'
      path: '/api/spotify/token'
      fullPath: '/api/spotify/token'
      preLoaderRoute: typeof ApiSpotifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/refresh': {
      id: '/api/spotify/refresh'
      path: '/api/spotify/refresh'
      fullPath: '/api/spotify/refresh'
      preLoaderRoute: typeof ApiSpotifyRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/digest': {
      id: '/api/memory/digest'
      path: '/digest'
      fullPath: '/api/memory/digest'
      preLoaderRoute: typeof ApiMemoryDigestRouteImport
      parentRoute: typeof ApiMemoryRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHealthRoute: typeof AppHealthRoute
  AppJournalRoute: typeof AppJournalRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppNotesRoute: typeof AppNotesRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHealthRoute: AppHealthRoute,
  AppJournalRoute: AppJournalRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppNotesRoute: AppNotesRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiMemoryRouteChildren {
  ApiMemoryDigestRoute: typeof ApiMemoryDigestRoute
}

const ApiMemoryRouteChildren: ApiMemoryRouteChildren = {
  ApiMemoryDigestRoute: ApiMemoryDigestRoute,
}

const ApiMemoryRouteWithChildren = ApiMemoryRoute._addFileChildren(
  ApiMemoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConversationsRoute: ApiConversationsRoute,
  ApiDataRoute: ApiDataRoute,
  ApiInsightsRoute: ApiInsightsRoute,
  ApiMemoryRoute: ApiMemoryRouteWithChildren,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiUsageSummaryRoute: ApiUsageSummaryRoute,
  ApiSpotifyRefreshRoute: ApiSpotifyRefreshRoute,
  ApiSpotifyTokenRoute: ApiSpotifyTokenRoute,
  ApiVoiceDeepgramTokenRoute: ApiVoiceDeepgramTokenRoute,
  ApiVoiceSessionRoute: ApiVoiceSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
